### ISSUE TITLE
Current version is outdated

### ISSUE THREAD

**Issue by Umeaboy** [flathub/org.firestormviewer.FirestormViewer#14]
I got pop-up window when starting Firestorm Viewer telling me that 6.6.3 is released, but there's no update when I run flatpak update.

kristoffer@kristoffer-N550JK:~$ flatpak update
Looking for updates…
Nothing to do.

Please push it.

**Comment by p1u3o** [comment]
The update was pulled, just waiting for Flathub to ship it (an hour or two)

**Comment by Umeaboy** [comment]
Am I the only person still not seeing the update?
On https://flathub.org/apps/details/org.firestormviewer.FirestormViewer I read 6.3.9.58205 on version and it was updated May 28, 2020.

Did you push an update or not?

flatpak list shows:

Firestorm Viewer   …viewer.FirestormViewer 6.3.9.58205 stable     system

I ask for this to be dealt with A.S.A.P.
