### ISSUE TITLE
Flatpak cannot use system notifications

### ISSUE THREAD

**Issue by Kivarnis** [flathub/org.firestormviewer.FirestormViewer#15]
On Fedora 36 (I presume this doesn't matter) on KDE this flatpak cannot use notifications. I use the program Flatseal to give it permissions and it's entirely grayed out. I'm not sure what to do here but this is a extremely major annoyance.

**Comment by p1u3o** [comment]
Is this still an issue? It should come with notification permissions

I still receive notifications on GNOME.
