### ISSUE TITLE
app updated flatpak version needs updating

### ISSUE THREAD

**Issue by kennythedragon** [flathub/org.firestormviewer.FirestormViewer#22]
firestorm viewer released new version on all platforms. cant get the non flatpak version to run on steamos without gconftools-2

**Comment by p1u3o** [comment]
This has been delayed because the upstream Firestorm made a change that breaks running on non-Ubuntu distros, which includes the Flatpak runtime.

see https://github.com/flathub/org.firestormviewer.FirestormViewer/pull/21

Fortunately, a work around has been found so an updated version should be out within the next 24 hours or so.

**Comment by kennythedragon** [comment]
> This has been delayed because the upstream Firestorm made a change that breaks running on non-Ubuntu distros, which includes the Flatpak runtime.
> 
> see #21
> 
> Fortunately, a work around has been found so an updated version should be out within the next 24 hours or so.

Ah ok. Meantime set up the windows one on wine. Not as memory efficient but it works

**Comment by p1u3o** [comment]
Using Wine may be where this Flatpak ends up, I don't see why there would be any significant memory overhead of using Wine, if anything I'd expect a Wine version to run better.

**Comment by kennythedragon** [comment]
> Using Wine may be where this Flatpak ends up, I don't see why there would be any significant memory overhead of using Wine, if anything I'd expect a Wine version to run better.

I am finding on wine instead of 8gb of combined memory usage (device has no separate ram for the gpu) I am seeing 12gb used out of 16 available. Flatpak version uses at most 8 leaving the rest free for othe uses.

**Comment by kennythedragon** [comment]
> Using Wine may be where this Flatpak ends up, I don't see why there would be any significant memory overhead of using Wine, if anything I'd expect a Wine version to run better.

Often firestorm on Wine for me at least in places on the lowest setting still eats up the last ram and crashes as the system doesn't seem to know what to put to the swap file. 8gb swap and not even 500mb used.

**Comment by HadetTheUndying** [comment]
My PR is updated and working. Including Ubuntu's libxcrypt was the right call we should be good for now.
