### ISSUE TITLE
Cant Install: Server return status 404

### ISSUE THREAD

**Issue by bignexus** [flathub/org.firestormviewer.FirestormViewer#24]
Hello, i have make a manuell install... and have a error msg on end:

flatpak install flathub org.firestormviewer.FirestormViewer
Looking for matches…
Required runtime for org.firestormviewer.FirestormViewer/x86_64/stable (runtime/org.freedesktop.Platform/x86_64/21.08) found in remote flathub
Do you want to install it? [Y/n]: 
Info: org.freedesktop.Platform//21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: org.freedesktop.Platform.Compat.i386//21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: (pinned) org.freedesktop.Platform.GL.default//21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.

org.firestormviewer.FirestormViewer permissions:
    ipc                    network       pulseaudio          x11
    dri                    multiarch     file access [1]     dbus access [2]
    bus ownership [3]

    [1] xdg-desktop, xdg-documents, xdg-download, xdg-music, xdg-pictures,
        xdg-run/app/com.discordapp.Discord:create, ~/.firestorm_x64:create
    [2] org.freedesktop.Notifications, org.freedesktop.secrets
    [3] com.secondlife.ViewerAppAPIService
        KENNUNG                                Zweig    Op   Remote    Download
 1. [✓] org.freedesktop.Platform.Compat.i386   21.08    i    flathub   126,2 MB / 102,3 MB
 2. [✓] org.freedesktop.Platform.Locale        21.08    i    flathub     1,5 MB / 326,8 MB
 3. [✓] org.freedesktop.Platform               21.08    i    flathub   186,2 MB / 202,1 MB
 4. [✗] org.firestormviewer.FirestormViewer    stable   i    flathub    13,0 MB / 173,1 MB

Error: Während des Herunterladens von https://downloads.firestormviewer.org/linux/Phoenix-FirestormOS-Releasex64-6-6-14-69596.tar.xz: Server returned status 404: Not Found
Fehler: Failed to installieren org.firestormviewer.FirestormViewer: Während des Herunterladens von https://downloads.firestormviewer.org/linux/Phoenix-FirestormOS-Releasex64-6-6-14-69596.tar.xz: Server returned status 404: Not Found

Isee on Issus #20 the same with 403 

 isee the issue with a newer (Flatpak) version... took me a second but i noticed it's the same issue but different tar xz version .. the : at the end of the URL again.. so ithink its help to clean the link without : of the end

**Comment by HadetTheUndying** [comment]
Please test the latest PR.

**Comment by bignexus** [comment]
the right download link is https://downloads.firestormviewer.org/release/linux/Phoenix-Firestorm-Releasex64-6-6-14-69596.tar.xz

**Comment by HadetTheUndying** [comment]
Please test the PR I linked it should be working now

**Comment by HadetTheUndying** [comment]
https://github.com/flathub/org.firestormviewer.FirestormViewer/pull/25

**Comment by bignexus** [comment]
flatpak install flathub org.firestormviewer.FirestormViewer
Looking for matches…
Remote ‘flathub’ found in multiple installations:

   1) system
   2) user

Which do you want to use (0 to abort)? [0-2]: 1
Required runtime for org.firestormviewer.FirestormViewer/x86_64/stable (runtime/org.freedesktop.Platform/x86_64/21.08) found in remote flathub
Do you want to install it? [Y/n]: y
Info: org.freedesktop.Platform//21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: org.freedesktop.Platform.Compat.i386//21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: (pinned) org.freedesktop.Platform.GL.default//21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.

org.firestormviewer.FirestormViewer permissions:
    ipc                    network       pulseaudio          x11
    dri                    multiarch     file access [1]     dbus access [2]
    bus ownership [3]

    [1] xdg-desktop, xdg-documents, xdg-download, xdg-music, xdg-pictures,
        xdg-run/app/com.discordapp.Discord:create, ~/.firestorm_x64:create
    [2] org.freedesktop.Notifications, org.freedesktop.secrets
    [3] com.secondlife.ViewerAppAPIService


        KENNUNG                              Zweig  Op Remote  Download
 1. [✓] org.freedesktop.Platform.Compat.i386 21.08  i  flathub 112,4 MB / 102,3 MB
 2. [✓] org.freedesktop.Platform.GL.default  21.08  i  flathub 129,5 MB / 129,8 MB
 3. [✓] org.freedesktop.Platform.Locale      21.08  i  flathub   1,5 MB / 326,8 MB
 4. [✓] org.freedesktop.Platform.openh264    2.0    i  flathub   1,5 MB / 1,5 MB
 5. [✓] org.freedesktop.Platform             21.08  i  flathub 185,0 MB / 202,1 MB
 6. [✗] org.firestormviewer.FirestormViewer  stable i  flathub  13,7 MB / 173,1 MB

Error: Während des Herunterladens von https://downloads.firestormviewer.org/linux/Phoenix-FirestormOS-Releasex64-6-6-14-69596.tar.xz: Server returned status 404: Not Found
Fehler: Failed to installieren org.firestormviewer.FirestormViewer: Während des Herunterladens von https://downloads.firestormviewer.org/linux/Phoenix-FirestormOS-Releasex64-6-6-14-69596.tar.xz: Server returned status 404: Not Found

still wrong link

**Comment by HadetTheUndying** [comment]
> flatpak install flathub org.firestormviewer.FirestormViewer Looking for matches… Remote ‘flathub’ found in multiple installations:
> 
>     1. system
> 
>     2. user
> 
> 
> Which do you want to use (0 to abort)? [0-2]: 1 Required runtime for org.firestormviewer.FirestormViewer/x86_64/stable (runtime/org.freedesktop.Platform/x86_64/21.08) found in remote flathub Do you want to install it? [Y/n]: y Info: org.freedesktop.Platform//21.08 is end-of-life, with reason: org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version. Info: org.freedesktop.Platform.Compat.i386//21.08 is end-of-life, with reason: org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version. Info: (pinned) org.freedesktop.Platform.GL.default//21.08 is end-of-life, with reason: org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
> 
> org.firestormviewer.FirestormViewer permissions: ipc network pulseaudio x11 dri multiarch file access [1] dbus access [2] bus ownership [3]
> 
> ```
> [1] xdg-desktop, xdg-documents, xdg-download, xdg-music, xdg-pictures,
>     xdg-run/app/com.discordapp.Discord:create, ~/.firestorm_x64:create
> [2] org.freedesktop.Notifications, org.freedesktop.secrets
> [3] com.secondlife.ViewerAppAPIService
> 
> 
>     KENNUNG                              Zweig  Op Remote  Download
> ```
> 
>     1. [✓] org.freedesktop.Platform.Compat.i386 21.08  i  flathub 112,4 MB / 102,3 MB
> 
>     2. [✓] org.freedesktop.Platform.GL.default  21.08  i  flathub 129,5 MB / 129,8 MB
> 
>     3. [✓] org.freedesktop.Platform.Locale      21.08  i  flathub   1,5 MB / 326,8 MB
> 
>     4. [✓] org.freedesktop.Platform.openh264    2.0    i  flathub   1,5 MB / 1,5 MB
> 
>     5. [✓] org.freedesktop.Platform             21.08  i  flathub 185,0 MB / 202,1 MB
> 
>     6. [✗] org.firestormviewer.FirestormViewer  stable i  flathub  13,7 MB / 173,1 MB
> 
> 
> Error: Während des Herunterladens von https://downloads.firestormviewer.org/linux/Phoenix-FirestormOS-Releasex64-6-6-14-69596.tar.xz: Server returned status 404: Not Found Fehler: Failed to installieren org.firestormviewer.FirestormViewer: Während des Herunterladens von https://downloads.firestormviewer.org/linux/Phoenix-FirestormOS-Releasex64-6-6-14-69596.tar.xz: Server returned status 404: Not Found
> 
> still wrong link

Please read the PR

Try running
`flatpak install --user https://dl.flathub.org/build-repo/64746/org.firestormviewer.FirestormViewer.flatpakref`

We haven't pushed the update yet so running the regular install command is still going to have the same issue as before.

**Comment by bignexus** [comment]
flatpak install --user https://dl.flathub.org/build-repo/64746/org.firestormviewer.FirestormViewer.flatpakref
Fehler: Can't load uri https://dl.flathub.org/build-repo/64746/org.firestormviewer.FirestormViewer.flatpakref: Server returned status 404: Not Found

**Comment by p1u3o** [comment]
> flatpak install --user https://dl.flathub.org/build-repo/64746/org.firestormviewer.FirestormViewer.flatpakref Fehler: Can't load uri https://dl.flathub.org/build-repo/64746/org.firestormviewer.FirestormViewer.flatpakref: Server returned status 404: Not Found

Flathub doesn't keep unmerged builds for long, this is merged now so it will be life within a few hours.
