### ISSUE TITLE
flatpak issue

### ISSUE THREAD

**Issue by Yudibear12** [flathub/org.firestormviewer.FirestormViewer#26]
Aborted due to failure (While downloading https://downloads.firestormviewer.org/linux/Phoenix-FirestormOS-Releasex64-6-6-14-69596.tar.xz: Server returned status 404)

**Comment by bignexus** [comment]
the right download link is: https://downloads.firestormviewer.org/release/linux/Phoenix-Firestorm-Releasex64-6-6-14-69596.tar.xz

**Comment by bignexus** [comment]
flatpak install flathub org.firestormviewer.FirestormViewer
Looking for matches…
Remote ‘flathub’ found in multiple installations:

   1) system
   2) user

Which do you want to use (0 to abort)? [0-2]: 1
Required runtime for org.firestormviewer.FirestormViewer/x86_64/stable (runtime/org.freedesktop.Platform/x86_64/21.08) found in remote flathub
Do you want to install it? [Y/n]: y
Info: org.freedesktop.Platform//21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: org.freedesktop.Platform.Compat.i386//21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: (pinned) org.freedesktop.Platform.GL.default//21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.

org.firestormviewer.FirestormViewer permissions:
    ipc                    network       pulseaudio          x11
    dri                    multiarch     file access [1]     dbus access [2]
    bus ownership [3]

    [1] xdg-desktop, xdg-documents, xdg-download, xdg-music, xdg-pictures,
        xdg-run/app/com.discordapp.Discord:create, ~/.firestorm_x64:create
    [2] org.freedesktop.Notifications, org.freedesktop.secrets
    [3] com.secondlife.ViewerAppAPIService


        KENNUNG                              Zweig  Op Remote  Download
 1. [✓] org.freedesktop.Platform.Compat.i386 21.08  i  flathub 112,4 MB / 102,3 MB
 2. [✓] org.freedesktop.Platform.GL.default  21.08  i  flathub 129,5 MB / 129,8 MB
 3. [✓] org.freedesktop.Platform.Locale      21.08  i  flathub   1,5 MB / 326,8 MB
 4. [✓] org.freedesktop.Platform.openh264    2.0    i  flathub   1,5 MB / 1,5 MB
 5. [✓] org.freedesktop.Platform             21.08  i  flathub 185,0 MB / 202,1 MB
 6. [✗] org.firestormviewer.FirestormViewer  stable i  flathub  13,7 MB / 173,1 MB

Error: Während des Herunterladens von https://downloads.firestormviewer.org/linux/Phoenix-FirestormOS-Releasex64-6-6-14-69596.tar.xz: Server returned status 404: Not Found
Fehler: Failed to installieren org.firestormviewer.FirestormViewer: Während des Herunterladens von https://downloads.firestormviewer.org/linux/Phoenix-FirestormOS-Releasex64-6-6-14-69596.tar.xz: Server returned status 404: Not Found

still the wrong link

**Comment by Yudibear12** [comment]
Yes

**Comment by p1u3o** [comment]
This should be fixed.
