### ISSUE TITLE
Unable to install flatpak from flathub

### ISSUE THREAD

**Issue by datshicray** [flathub/org.firestormviewer.FirestormViewer#28]
I have been unable to install the flatpak on Spiral Linux Xfce (Debian 13 “Trixie”) [https://sparkylinux.org/download/rolling/](https://sparkylinux.org/download/rolling/) with the latest kernel (6.5). 

```
Intel(R) Celeron(R) CPU  N3060  @ 1.60GHz (1599.95 MHz)
 Memory: 3999 MB (Used: 1734 MB)
 Concurrency: 2
 Graphics Card Vendor: Intel
 Graphics Card: Intel(R) HD Graphics 400
 Graphics Card Memory: 1024 MB
```

**Comment by HadetTheUndying** [comment]
> I have been unable to install the flatpak on Spiral Linux Xfce (Debian 13 “Trixie”) https://sparkylinux.org/download/rolling/ with the latest kernel (6.5).
> 
> ```
> Intel(R) Celeron(R) CPU  N3060  @ 1.60GHz (1599.95 MHz)
>  Memory: 3999 MB (Used: 1734 MB)
>  Concurrency: 2
>  Graphics Card Vendor: Intel
>  Graphics Card: Intel(R) HD Graphics 400
>  Graphics Card Memory: 1024 MB
> ```

Can you provide some logs when attempting to install from the CLI? I won't be around for a bit today but I can help you when I get home.

**Comment by datshicray** [comment]
I wiped the system and did a fresh install to re-create the issue and now, it's working. I have no idea why it was not working before.

`└─(21:45:11)──> neofetch                                                            ──(Sun,Nov26)─┘
       _,met$$$$$gg.          xox@xox 
    ,g$$$$$$$$$$$$$$$P.       ------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 12 (bookworm) x86_64 
 ,$$P'              `$$$.     Host: HP Stream Laptop 14-ax0XX 
',$$P       ,ggs.     `$$b:   Kernel: 6.5.0-0.deb12.1-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 27 mins 
 $$P      d$'     ,    $$P    Packages: 1616 (dpkg), 10 (flatpak) 
 $$:      $$.   -    ,d$$'    Shell: zsh 5.9 
 $$;      Y$b._   _,d$P'      Resolution: 1366x768 
 Y$$.    `.`"Y$$$$P"'         DE: Xfce 4.18 
 `$$b      "-.__              WM: Xfwm4 
  `Y$$                        WM Theme: Numix 
   `Y$$.                      Theme: Pop-dark [GTK2] 
     `$$b.                    Icons: Pop [GTK2] 
       `Y$$b.                 Terminal: xfce4-terminal 
          `"Y$b._             Terminal Font: Monospace 11 
              `"""            CPU: Intel Celeron N3060 (2) @ 2.480GHz 
                              GPU: Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx 
                              Memory: 1429MiB / 3815MiB 
`

`└─(21:39:57)──> flatpak install flathub org.firestormviewer.FirestormViewer         ──(Sun,Nov26)─┘
Looking for matches…
Required runtime for org.firestormviewer.FirestormViewer/x86_64/stable (runtime/org.freedesktop.Platform/x86_64/22.08) found in remote flathub
Do you want to install it? [Y/n]: y

org.firestormviewer.FirestormViewer permissions:
    ipc                       network           pulseaudio              x11
    dri                       multiarch         file access [1]         dbus access [2]
    bus ownership [3]

    [1] xdg-desktop, xdg-documents, xdg-download, xdg-music, xdg-pictures,
        xdg-run/app/com.discordapp.Discord:create, ~/.firestorm_x64:create
    [2] org.freedesktop.Notifications, org.freedesktop.secrets
    [3] com.secondlife.ViewerAppAPIService


        ID                                      Branch         Op   Remote    Download
 1. [✓] org.freedesktop.Platform.Compat.i386    22.08          i    flathub   102.8 MB / 103.7 MB
 2. [✓] org.freedesktop.Platform.GL.default     22.08          i    flathub   143.5 MB / 143.1 MB
 3. [✓] org.freedesktop.Platform.GL.default     22.08-extra    i    flathub    16.3 MB / 143.1 MB
 4. [✓] org.freedesktop.Platform.Locale         22.08          i    flathub    17.8 kB / 333.4 MB
 5. [✓] org.freedesktop.Platform.VAAPI.Intel    22.08          i    flathub    13.3 MB / 13.4 MB
 6. [✓] org.freedesktop.Platform.openh264       2.2.0          i    flathub     1.2 MB / 944.3 kB
 7. [✓] org.gtk.Gtk3theme.Pop-dark              3.22           i    flathub   230.3 kB / 226.0 kB
 8. [✓] org.freedesktop.Platform                22.08          i    flathub   189.2 MB / 211.8 MB
 9. [✓] org.firestormviewer.FirestormViewer     stable         i    flathub   176.4 MB / 173.1 MB

Installation complete.
`
