### ISSUE TITLE
not possible to install flatpak

### ISSUE THREAD

**Issue by freddii** [flathub/org.firestormviewer.FirestormViewer#5]
installing from commandline with:
$ flatpak install flathub org.firestormviewer.FirestormViewer

Error: Falsche Größe für Extradaten https://downloads.firestormviewer.org/linux/Phoenix_Firestorm-Release_x86_64_6.4.21.64531.tar.xz
Fehler: Failed to installieren org.firestormviewer.FirestormViewer: Falsche Größe für Extradaten https://downloads.firestormviewer.org/linux/Phoenix_Firestorm-Release_x86_64_6.4.21.64531.tar.xz

Installing from "Software":
![firestorm-flatpak](https://user-images.githubusercontent.com/7213207/147692708-8e5f32f4-76db-4930-807b-64c2c2e65acc.png)

**Comment by p1u3o** [comment]
Can you try again?

**Comment by freddii** [comment]
works now. Do you have an idea why it failed before?

**Comment by p1u3o** [comment]
> works now. Do you have an idea why it failed before?

It has to download assets from Firestorm and I presume the site was down
