### ISSUE TITLE
Ascii fonts issue

### ISSUE THREAD

**Issue by Silencer26** [flathub/org.firestormviewer.FirestormViewer#7]
Certain special ascii character fonts do not show up correctly in both gestures and custom avatar names since the latest update of Firestorm Flatpak. I do want to emphasize that I am not too familiar with linux yet so perhaps I am doing something wrong, but it did work fine for me until I downloaded the newest update. 
I am Running Pop OS! 21.10 with Norwegian language packs.
![SL Character Sheet](https://user-images.githubusercontent.com/102294043/159948270-26f8de5b-aa54-44eb-864f-7a8249f72213.png)
![Firestorm Bug](https://user-images.githubusercontent.com/102294043/159899581-9168a6c3-f206-417b-9177-0e940254121f.png)

I have downloaded Firestorm directly from firestormviewer.org and the problem is gone so I can confirm it is an issue with the flatpak version only, as shown by the screenshot below:
![Confirmed Ascii Issue](https://user-images.githubusercontent.com/102294043/164700933-50bc6a09-b417-4e02-8cbd-70f7c68840a6.png)

**Comment by p1u3o** [comment]
I am not too sure on the cause of this.. perhaps its a missing font from the Freedesktop runtime

**Comment by Silencer26** [comment]
Perhaps, I am not sure how to fix it myself as I am pretty new to using linux as a daily driver, but yeah through trial and error when I run it directly once downloaded and extracted from the webpage, the fonts work fine. I did check where the flatpak version was installed and it does contain the actual fonts and everything should in theory work..

**Comment by Silencer26** [comment]
Today I got an upgrade to PoP OS! Which brought it up to version 22.04 LTS and it seemed it also updated the freedesktop runtime in the process, but sadly the problem still persists for me with flatpak firestorm.

**Comment by HadetTheUndying** [comment]
The fonts will likely need to be part of the flatpak container. I'll look into what needs to be done for this.

**Comment by p1u3o** [comment]
> The fonts will likely need to be part of the flatpak container. I'll look into what needs to be done for this.

I had a look to see if there was any changed fonts with the new runtime and couldn't find anything that stuck out.

**Comment by Silencer26** [comment]
> > The fonts will likely need to be part of the flatpak container. I'll look into what needs to be done for this.
> 
> I had a look to see if there was any changed fonts with the new runtime and couldn't find anything that stuck out.

Yeah I also had a look in the files but I could not find any fonts that seem to be missing so I am not sure what is causing this at all.

**Comment by HadetTheUndying** [comment]
I think this is a general flatpak issue where flatpak doesn't have access to system fonts for specific unicode glyphs. There's a couple open issues about this in various repos. I'm having trouble finding them now though. Will try to link later when I have time.

**Comment by Silencer26** [comment]
> I think this is a general flatpak issue where flatpak doesn't have access to system fonts for specific unicode glyphs. There's a couple open issues about this in various repos. I'm having trouble finding them now though. Will try to link later when I have time.

That is very possible, but if that is the case it must have happened when the latest flatpak version of firestorm was put together, because the previous version of firestorm flatpak, did not have this issue at all.

**Comment by Silencer26** [comment]
I have tested and the ascii issue still persists in Firestorm 6.6.3 (67470), again only in the flatpak version.

**Comment by HadetTheUndying** [comment]
> I have tested and the ascii issue still persists in Firestorm 6.6.3 (67470), again only in the flatpak version.

Operate under the assumption that the issue is still present until a PR is opened to address it or the issue is closed. The only PRs that have been made recently are version bumps. You are welcome to try and fix the issue yourself. 

I have this issue with a few other apps but I believe Spotify did solve it, that would be a good place to look.

**Comment by Silencer26** [comment]
I have tested and the ascii issue still persists in Firestorm 6.6.3 (67470), again only in the flatpak version.

> > I have tested and the ascii issue still persists in Firestorm 6.6.3 (67470), again only in the flatpak version.
> 
> Operate under the assumption that the issue is still present until a PR is opened to address it or the issue is closed. The only PRs that have been made recently are version bumps. You are welcome to try and fix the issue yourself.
> 
> I have this issue with a few other apps but I believe Spotify did solve it, that would be a good place to look.

Sadly I do not have the technical knowledge with Linux/Flatpak in order to fix this issue myself (at least not yet), but I will keep a close watch on this post in the hopes that someone else does.

**Comment by p1u3o** [comment]
@HadetTheUndying I don't think this is an issue anymore.

**Comment by HadetTheUndying** [comment]
> @HadetTheUndying I don't think this is an issue anymore.

This issue can definitely be closed as well. I verified that ASCII names are now working correctly with the latest PR.

**Comment by Silencer26** [comment]
I have confirmed that this issue has been fixed in the latest version so I am closing it down. Thanks everyone for your input and help with this.
