### ISSUE TITLE
Firestorm for Opensim

### ISSUE THREAD

**Issue by trawell** [flathub/org.firestormviewer.FirestormViewer#8]
Hello,
The viewer is a great thing, even Voice works.
Can you do the same with Firestorm Viewer for Opensim ?
I hope I am in the right place with my request.
Many greetings
Trawell

**Comment by HadetTheUndying** [comment]
You could probably accomplish this locally by just changing the target tarball location in the org.firestormviewer.FirestormViewer.json file.

**Comment by Nicky-D** [comment]
We do not have a real difference between OS/SL for Linux (there used to when when LL still have a Havok blob for Linux and we could include Havok in the Linux builds).
Thus I'd suggest making the OS Linux builds the default in your Flatpak

**Comment by p1u3o** [comment]
I'll swap the builds over

**Comment by HadetTheUndying** [comment]
> I'll swap the builds over

It appears this never happened. Do you mind if I open a PR for this?

**Comment by p1u3o** [comment]
Sorry, RL got hectic and I haven't had much time to keep this maintained.
